trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: katalonTask@0
  displayName: 'Execute Katalon Studio project'
  inputs:
    version: '7.0.1'
    executeArgs: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Regression Suite/Test Suite Collection/TS Collection for parallel run"'
- task: CmdLine@2
  inputs:
    script: |
      cd /Applications/Katalon\ Studio\ Engine.app/Contents/MacOS
      
      ./katalonc -noSplash -runMode=console -projectPath="/Users/katalon/My_Source_Code/KatalonStudio/Katalon_Web_AzureDevops/Katalon_Web_AzureDevops.prj" -retry=0 -testSuiteCollectionPath="Test Suites/Regression Suite/Test Suite Collection/TS Collection for parallel run" -apiKey="ac0360a1-d23b-4b80-b61f-c5291b4cc878" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true