trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: katalonTask@0
  displayName: 'Execute Katalon Studio project'
  inputs:
    version: '8.0.1'
    executeArgs: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Regression Suite/Test Suite Collection/TS Collection for parallel run" -apiKey=ac0360a1-d23b-4b80-b61f-c5291b4cc878'